### ISSUE TITLE
Repository description is wrong (Not `kustomize build` but `kubectl diff`)

### ISSUE THREAD

**Issue by suzuki-shunsuke** [hirosassa/ksnotify#28]
I'm sorry if I'm misunderstanding, but I suspect the repository description `A CLI command to parse kustomize build result and notify it to GitLab` is wrong.

I guess the correct description is `A CLI command to parse kubectl diff result and notify it to GitLab`.

<img width="648" alt="image" src="https://user-images.githubusercontent.com/13323303/200174360-237b909f-5799-439c-8fe7-437308b51f84.png">

**Comment by hirosassa** [comment]
@suzuki-shunsuke Oh! You are right! I'll fix this shortly.

**Comment by hirosassa** [comment]
Fixed. Thanks for your suggestion!

![Screen Shot 2022-11-07 at 5 51 51](https://user-images.githubusercontent.com/423223/200194504-8200fb72-975c-47b1-9623-106be7775d58.png)
